version: "3.9"

services:
  frigate:
    build:
      context: .
      dockerfile: Dockerfile.deepocsort
    container_name: frigate
    restart: unless-stopped
    ports:
      - "5000:5000"
    volumes:
      - ./config:/config
      - ./input:/media/frigate
      - type: tmpfs
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    environment:
      - FRIGATE_RTSP_PASSWORD=password
    devices:
      - /dev/bus/usb:/dev/bus/usb
    privileged: true
    shm_size: "64mb"
